version: "3"

services:
  db-cache:
    image: redis
    container_name: cache-db
    volumes:
      - "/home/ayondip/final-project-db/redis:/data"
    ports:
      - "6379:6379"
    command: redis-server --save 30 1 --loglevel warning
  db-mongo:
    image: mongo
    container_name: mongo-database
    volumes:
      - "/home/ayondip/final-project-db/mongodb:/data/db"
    ports:
      - "27017:27017"
  db-postgress:
    image: postgres
    container_name: postgres-database
    volumes:
      - "/home/ayondip/final-project-db/postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=mydb
