version: "3"

services:
  db-cache:
    image: redis
    container_name: cache-db
    volumes:
      - "/home/ayondip/final-project-db/redis:/data"
    ports:
      - "6379:6379"
    command: redis-server --save 30 1 --loglevel warning
  db-postgress:
    image: postgres
    container_name: postgres-database
    volumes:
      - "/home/ayondip/final-project-db/postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=mydb
  message-queue:
    image: rabbitmq:3.8-management
    container_name: message-queue
    volumes:
      - "/home/ayondip/final-project-db/rabbitmq:/var/lib/rabbitmq"
    ports:
      - "8080:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass
