version: '3'

services:
  db:
    image: mongo
    container_name: social-database
    ports:
      - "27017:27017"
  auth_server:
    image: auth-server
    env_file:
      - ./auth_server/src/.env/.env
    depends_on:
      - db
    container_name: auth_server
    build:
      context: ./auth_server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"