name: Test-Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - dev
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    steps:
        - uses: actions/checkout@v3
        - name: Use Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '16.x'
        - name: Build Auth service 
          run: |
            cd auth_service
            npm install
            npm run build
        - name: Build Resourse service
          run: |
            cd resource_service 
            npm install
            npm run build
        - name: Build fanout service
          run: |
            cd fanout_service 
            npm install
            npm run build
        - name: Build notification service
          run: |
            cd notification_service 
            npm install
            npm run build     