name: Test-Build

on:
  push:
    branches:
      - master
  pull_request:
    branch:
      - master
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    steps:
        - uses: actions/checkout@v3
        - name: Use Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '16.x'
        - name: Install dependencies
          run: |
            cd auth_server 
            npm install
            npm run build
        - name: cr
          run: ls
             